spring.application.name=roomhub
spring.datasource.url=jdbc:mysql://localhost:3306/roomhub
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8088
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.default-property-inclusion=non_null
spring.jpa.open-in-view=false

application.security.jwt.secret-key=cm9vbWh1YlNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNg==
application.security.jwt.access-token-expiration=900000
application.security.jwt.refresh-token-expiration=604800000

application.cors.allowed-origins=http://localhost:3000,http://localhost:5173
application.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
application.cors.allowed-headers=*
application.cors.allow-credentials=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.root=INFO
logging.level.com.chinh.roomhub=INFO
logging.level.org.springframework.security=INFO
